server:
  port: 8081

spring:
  application:
    name: micro-catalog-service

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'